// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYC_o30JtH9gw9yGxc6xVZFJZUNu2h26k',
    appId: '1:882760979434:android:f28777367db20006659893',
    messagingSenderId: '882760979434',
    projectId: 'flutter-chat-app-97175',
    storageBucket: 'flutter-chat-app-97175.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxSR_4AQ0dBkyvSF9Iwe1vGA1bfZzgK8M',
    appId: '1:882760979434:ios:7df26929784f6549659893',
    messagingSenderId: '882760979434',
    projectId: 'flutter-chat-app-97175',
    storageBucket: 'flutter-chat-app-97175.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkH1t3KbqhT3QMTTtKaGYvPIJG2Ig8tiU',
    appId: '1:882760979434:web:654e14edc04c53ea659893',
    messagingSenderId: '882760979434',
    projectId: 'flutter-chat-app-97175',
    authDomain: 'flutter-chat-app-97175.firebaseapp.com',
    storageBucket: 'flutter-chat-app-97175.firebasestorage.app',
    measurementId: 'G-5S8G89PK3R',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxSR_4AQ0dBkyvSF9Iwe1vGA1bfZzgK8M',
    appId: '1:882760979434:ios:7df26929784f6549659893',
    messagingSenderId: '882760979434',
    projectId: 'flutter-chat-app-97175',
    storageBucket: 'flutter-chat-app-97175.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkH1t3KbqhT3QMTTtKaGYvPIJG2Ig8tiU',
    appId: '1:882760979434:web:ee6474bcb930c513659893',
    messagingSenderId: '882760979434',
    projectId: 'flutter-chat-app-97175',
    authDomain: 'flutter-chat-app-97175.firebaseapp.com',
    storageBucket: 'flutter-chat-app-97175.firebasestorage.app',
    measurementId: 'G-5QNE5R6ER2',
  );

}